/* tslint:disable */
/* eslint-disable */
/**
 * ITAM Chat Backend
 * Backend for a messenger app. Provides JWT auth, user search, chats with previews, chat contents with pagination, and real-time messaging via WebSockets.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

